server:
  port: ${PORT:9009}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

spring:
  application:
    name: eureka-service
  security:
    basic:
      enabled: true
    user:
      name: eureka-user
      password: eureka-pass